// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base/TeacherTestVS.proto

package com.qingqing.proto.find;

public final class TaapiFindTeacherForTAProto {
  private TaapiFindTeacherForTAProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TaapiFindTeacherDemandForTARequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TaapiFindTeacherDemandForTARequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 demand_id = 1;</code>
     *
     * <pre>
     *找老师请求ID
     * </pre>
     */
    boolean hasDemandId();
    /**
     * <code>optional int64 demand_id = 1;</code>
     *
     * <pre>
     *找老师请求ID
     * </pre>
     */
    long getDemandId();

    /**
     * <code>optional int32 grade_id = 2;</code>
     */
    boolean hasGradeId();
    /**
     * <code>optional int32 grade_id = 2;</code>
     */
    int getGradeId();

    /**
     * <code>optional int32 course_id = 3;</code>
     */
    boolean hasCourseId();
    /**
     * <code>optional int32 course_id = 3;</code>
     */
    int getCourseId();

    /**
     * <code>optional string address = 4;</code>
     */
    boolean hasAddress();
    /**
     * <code>optional string address = 4;</code>
     */
    java.lang.String getAddress();
    /**
     * <code>optional string address = 4;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>optional int64 create_time = 6;</code>
     *
     * <pre>
     *    optional FindTeacherRequestTyoe request_type = 5;
     * </pre>
     */
    boolean hasCreateTime();
    /**
     * <code>optional int64 create_time = 6;</code>
     *
     * <pre>
     *    optional FindTeacherRequestTyoe request_type = 5;
     * </pre>
     */
    long getCreateTime();

    /**
     * <code>optional string info = 9;</code>
     */
    boolean hasInfo();
    /**
     * <code>optional string info = 9;</code>
     */
    java.lang.String getInfo();
    /**
     * <code>optional string info = 9;</code>
     */
    com.google.protobuf.ByteString
        getInfoBytes();
  }
  /**
   * Protobuf type {@code TaapiFindTeacherDemandForTARequest}
   *
   * <pre>
   *4.7.0 新增 找老师请求信息
   * </pre>
   */
  public  static final class TaapiFindTeacherDemandForTARequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:TaapiFindTeacherDemandForTARequest)
      TaapiFindTeacherDemandForTARequestOrBuilder {
    // Use TaapiFindTeacherDemandForTARequest.newBuilder() to construct.
    private TaapiFindTeacherDemandForTARequest(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private TaapiFindTeacherDemandForTARequest() {
      demandId_ = 0L;
      gradeId_ = 0;
      courseId_ = 0;
      address_ = "";
      createTime_ = 0L;
      info_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TaapiFindTeacherDemandForTARequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              demandId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              gradeId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              courseId_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              address_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000010;
              createTime_ = input.readInt64();
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              info_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qingqing.proto.find.TaapiFindTeacherForTAProto.internal_static_TaapiFindTeacherDemandForTARequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qingqing.proto.find.TaapiFindTeacherForTAProto.internal_static_TaapiFindTeacherDemandForTARequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qingqing.proto.find.TaapiFindTeacherForTAProto.TaapiFindTeacherDemandForTARequest.class, com.qingqing.proto.find.TaapiFindTeacherForTAProto.TaapiFindTeacherDemandForTARequest.Builder.class);
    }

    private int bitField0_;
    public static final int DEMAND_ID_FIELD_NUMBER = 1;
    private long demandId_;
    /**
     * <code>optional int64 demand_id = 1;</code>
     *
     * <pre>
     *找老师请求ID
     * </pre>
     */
    public boolean hasDemandId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 demand_id = 1;</code>
     *
     * <pre>
     *找老师请求ID
     * </pre>
     */
    public long getDemandId() {
      return demandId_;
    }

    public static final int GRADE_ID_FIELD_NUMBER = 2;
    private int gradeId_;
    /**
     * <code>optional int32 grade_id = 2;</code>
     */
    public boolean hasGradeId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 grade_id = 2;</code>
     */
    public int getGradeId() {
      return gradeId_;
    }

    public static final int COURSE_ID_FIELD_NUMBER = 3;
    private int courseId_;
    /**
     * <code>optional int32 course_id = 3;</code>
     */
    public boolean hasCourseId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 course_id = 3;</code>
     */
    public int getCourseId() {
      return courseId_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 4;
    private volatile java.lang.Object address_;
    /**
     * <code>optional string address = 4;</code>
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string address = 4;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          address_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string address = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATE_TIME_FIELD_NUMBER = 6;
    private long createTime_;
    /**
     * <code>optional int64 create_time = 6;</code>
     *
     * <pre>
     *    optional FindTeacherRequestTyoe request_type = 5;
     * </pre>
     */
    public boolean hasCreateTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 create_time = 6;</code>
     *
     * <pre>
     *    optional FindTeacherRequestTyoe request_type = 5;
     * </pre>
     */
    public long getCreateTime() {
      return createTime_;
    }

    public static final int INFO_FIELD_NUMBER = 9;
    private volatile java.lang.Object info_;
    /**
     * <code>optional string info = 9;</code>
     */
    public boolean hasInfo() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string info = 9;</code>
     */
    public java.lang.String getInfo() {
      java.lang.Object ref = info_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          info_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string info = 9;</code>
     */
    public com.google.protobuf.ByteString
        getInfoBytes() {
      java.lang.Object ref = info_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        info_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, demandId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, gradeId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, courseId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getAddressBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(6, createTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(9, getInfoBytes());
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, demandId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, gradeId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, courseId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getAddressBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, createTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getInfoBytes());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.qingqing.proto.find.TaapiFindTeacherForTAProto.TaapiFindTeacherDemandForTARequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qingqing.proto.find.TaapiFindTeacherForTAProto.TaapiFindTeacherDemandForTARequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qingqing.proto.find.TaapiFindTeacherForTAProto.TaapiFindTeacherDemandForTARequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qingqing.proto.find.TaapiFindTeacherForTAProto.TaapiFindTeacherDemandForTARequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qingqing.proto.find.TaapiFindTeacherForTAProto.TaapiFindTeacherDemandForTARequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qingqing.proto.find.TaapiFindTeacherForTAProto.TaapiFindTeacherDemandForTARequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.qingqing.proto.find.TaapiFindTeacherForTAProto.TaapiFindTeacherDemandForTARequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.qingqing.proto.find.TaapiFindTeacherForTAProto.TaapiFindTeacherDemandForTARequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.qingqing.proto.find.TaapiFindTeacherForTAProto.TaapiFindTeacherDemandForTARequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qingqing.proto.find.TaapiFindTeacherForTAProto.TaapiFindTeacherDemandForTARequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qingqing.proto.find.TaapiFindTeacherForTAProto.TaapiFindTeacherDemandForTARequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TaapiFindTeacherDemandForTARequest}
     *
     * <pre>
     *4.7.0 新增 找老师请求信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TaapiFindTeacherDemandForTARequest)
        com.qingqing.proto.find.TaapiFindTeacherForTAProto.TaapiFindTeacherDemandForTARequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qingqing.proto.find.TaapiFindTeacherForTAProto.internal_static_TaapiFindTeacherDemandForTARequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qingqing.proto.find.TaapiFindTeacherForTAProto.internal_static_TaapiFindTeacherDemandForTARequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qingqing.proto.find.TaapiFindTeacherForTAProto.TaapiFindTeacherDemandForTARequest.class, com.qingqing.proto.find.TaapiFindTeacherForTAProto.TaapiFindTeacherDemandForTARequest.Builder.class);
      }

      // Construct using com.qingqing.proto.find.TaapiFindTeacherForTAProto.TaapiFindTeacherDemandForTARequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        demandId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        gradeId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        courseId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        address_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        createTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        info_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qingqing.proto.find.TaapiFindTeacherForTAProto.internal_static_TaapiFindTeacherDemandForTARequest_descriptor;
      }

      public com.qingqing.proto.find.TaapiFindTeacherForTAProto.TaapiFindTeacherDemandForTARequest getDefaultInstanceForType() {
        return com.qingqing.proto.find.TaapiFindTeacherForTAProto.TaapiFindTeacherDemandForTARequest.getDefaultInstance();
      }

      public com.qingqing.proto.find.TaapiFindTeacherForTAProto.TaapiFindTeacherDemandForTARequest build() {
        com.qingqing.proto.find.TaapiFindTeacherForTAProto.TaapiFindTeacherDemandForTARequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qingqing.proto.find.TaapiFindTeacherForTAProto.TaapiFindTeacherDemandForTARequest buildPartial() {
        com.qingqing.proto.find.TaapiFindTeacherForTAProto.TaapiFindTeacherDemandForTARequest result = new com.qingqing.proto.find.TaapiFindTeacherForTAProto.TaapiFindTeacherDemandForTARequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.demandId_ = demandId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.gradeId_ = gradeId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.courseId_ = courseId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.address_ = address_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.createTime_ = createTime_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.info_ = info_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qingqing.proto.find.TaapiFindTeacherForTAProto.TaapiFindTeacherDemandForTARequest) {
          return mergeFrom((com.qingqing.proto.find.TaapiFindTeacherForTAProto.TaapiFindTeacherDemandForTARequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qingqing.proto.find.TaapiFindTeacherForTAProto.TaapiFindTeacherDemandForTARequest other) {
        if (other == com.qingqing.proto.find.TaapiFindTeacherForTAProto.TaapiFindTeacherDemandForTARequest.getDefaultInstance()) return this;
        if (other.hasDemandId()) {
          setDemandId(other.getDemandId());
        }
        if (other.hasGradeId()) {
          setGradeId(other.getGradeId());
        }
        if (other.hasCourseId()) {
          setCourseId(other.getCourseId());
        }
        if (other.hasAddress()) {
          bitField0_ |= 0x00000008;
          address_ = other.address_;
          onChanged();
        }
        if (other.hasCreateTime()) {
          setCreateTime(other.getCreateTime());
        }
        if (other.hasInfo()) {
          bitField0_ |= 0x00000020;
          info_ = other.info_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qingqing.proto.find.TaapiFindTeacherForTAProto.TaapiFindTeacherDemandForTARequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qingqing.proto.find.TaapiFindTeacherForTAProto.TaapiFindTeacherDemandForTARequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long demandId_ ;
      /**
       * <code>optional int64 demand_id = 1;</code>
       *
       * <pre>
       *找老师请求ID
       * </pre>
       */
      public boolean hasDemandId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 demand_id = 1;</code>
       *
       * <pre>
       *找老师请求ID
       * </pre>
       */
      public long getDemandId() {
        return demandId_;
      }
      /**
       * <code>optional int64 demand_id = 1;</code>
       *
       * <pre>
       *找老师请求ID
       * </pre>
       */
      public Builder setDemandId(long value) {
        bitField0_ |= 0x00000001;
        demandId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 demand_id = 1;</code>
       *
       * <pre>
       *找老师请求ID
       * </pre>
       */
      public Builder clearDemandId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        demandId_ = 0L;
        onChanged();
        return this;
      }

      private int gradeId_ ;
      /**
       * <code>optional int32 grade_id = 2;</code>
       */
      public boolean hasGradeId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 grade_id = 2;</code>
       */
      public int getGradeId() {
        return gradeId_;
      }
      /**
       * <code>optional int32 grade_id = 2;</code>
       */
      public Builder setGradeId(int value) {
        bitField0_ |= 0x00000002;
        gradeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 grade_id = 2;</code>
       */
      public Builder clearGradeId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        gradeId_ = 0;
        onChanged();
        return this;
      }

      private int courseId_ ;
      /**
       * <code>optional int32 course_id = 3;</code>
       */
      public boolean hasCourseId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 course_id = 3;</code>
       */
      public int getCourseId() {
        return courseId_;
      }
      /**
       * <code>optional int32 course_id = 3;</code>
       */
      public Builder setCourseId(int value) {
        bitField0_ |= 0x00000004;
        courseId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 course_id = 3;</code>
       */
      public Builder clearCourseId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        courseId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>optional string address = 4;</code>
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string address = 4;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            address_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string address = 4;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string address = 4;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 4;</code>
       */
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000008);
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 4;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        address_ = value;
        onChanged();
        return this;
      }

      private long createTime_ ;
      /**
       * <code>optional int64 create_time = 6;</code>
       *
       * <pre>
       *    optional FindTeacherRequestTyoe request_type = 5;
       * </pre>
       */
      public boolean hasCreateTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 create_time = 6;</code>
       *
       * <pre>
       *    optional FindTeacherRequestTyoe request_type = 5;
       * </pre>
       */
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <code>optional int64 create_time = 6;</code>
       *
       * <pre>
       *    optional FindTeacherRequestTyoe request_type = 5;
       * </pre>
       */
      public Builder setCreateTime(long value) {
        bitField0_ |= 0x00000010;
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 create_time = 6;</code>
       *
       * <pre>
       *    optional FindTeacherRequestTyoe request_type = 5;
       * </pre>
       */
      public Builder clearCreateTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        createTime_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object info_ = "";
      /**
       * <code>optional string info = 9;</code>
       */
      public boolean hasInfo() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string info = 9;</code>
       */
      public java.lang.String getInfo() {
        java.lang.Object ref = info_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            info_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string info = 9;</code>
       */
      public com.google.protobuf.ByteString
          getInfoBytes() {
        java.lang.Object ref = info_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          info_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string info = 9;</code>
       */
      public Builder setInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        info_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string info = 9;</code>
       */
      public Builder clearInfo() {
        bitField0_ = (bitField0_ & ~0x00000020);
        info_ = getDefaultInstance().getInfo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string info = 9;</code>
       */
      public Builder setInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        info_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TaapiFindTeacherDemandForTARequest)
    }

    // @@protoc_insertion_point(class_scope:TaapiFindTeacherDemandForTARequest)
    private static final com.qingqing.proto.find.TaapiFindTeacherForTAProto.TaapiFindTeacherDemandForTARequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qingqing.proto.find.TaapiFindTeacherForTAProto.TaapiFindTeacherDemandForTARequest();
    }

    public static com.qingqing.proto.find.TaapiFindTeacherForTAProto.TaapiFindTeacherDemandForTARequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<TaapiFindTeacherDemandForTARequest> PARSER =
        new com.google.protobuf.AbstractParser<TaapiFindTeacherDemandForTARequest>() {
      public TaapiFindTeacherDemandForTARequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new TaapiFindTeacherDemandForTARequest(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TaapiFindTeacherDemandForTARequest> getParserForType() {
      return PARSER;
    }

    public com.qingqing.proto.find.TaapiFindTeacherForTAProto.TaapiFindTeacherDemandForTARequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TaapiFindTeacherDemandForTARequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TaapiFindTeacherDemandForTARequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030base/TeacherTestVS.proto\"\220\001\n\"TaapiFind" +
      "TeacherDemandForTARequest\022\021\n\tdemand_id\030\001" +
      " \001(\003\022\020\n\010grade_id\030\002 \001(\005\022\021\n\tcourse_id\030\003 \001(" +
      "\005\022\017\n\007address\030\004 \001(\t\022\023\n\013create_time\030\006 \001(\003\022" +
      "\014\n\004info\030\t \001(\tB@\n\027com.qingqing.proto.find" +
      "B\032TaapiFindTeacherForTAProto\242\002\010TaapiGPB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TaapiFindTeacherDemandForTARequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TaapiFindTeacherDemandForTARequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_TaapiFindTeacherDemandForTARequest_descriptor,
        new java.lang.String[] { "DemandId", "GradeId", "CourseId", "Address", "CreateTime", "Info", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
