package com.test;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1/Teachervs.proto

public final class Teachervs {
  private Teachervs() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TeacherInviteStudentRegisterRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TeacherInviteStudentRegisterRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string phone_number = 1;</code>
     */
    boolean hasPhoneNumber();
    /**
     * <code>optional string phone_number = 1;</code>
     */
    String getPhoneNumber();
    /**
     * <code>optional string phone_number = 1;</code>
     */
    com.google.protobuf.ByteString
        getPhoneNumberBytes();

    /**
     * <code>optional string captcha_code = 2;</code>
     *
     * <pre>
     * 验证码
     * </pre>
     */
    boolean hasCaptchaCode();
    /**
     * <code>optional string captcha_code = 2;</code>
     *
     * <pre>
     * 验证码
     * </pre>
     */
    String getCaptchaCode();
    /**
     * <code>optional string captcha_code = 2;</code>
     *
     * <pre>
     * 验证码
     * </pre>
     */
    com.google.protobuf.ByteString
        getCaptchaCodeBytes();

    /**
     * <code>optional string channel_no = 3;</code>
     */
    boolean hasChannelNo();
    /**
     * <code>optional string channel_no = 3;</code>
     */
    String getChannelNo();
    /**
     * <code>optional string channel_no = 3;</code>
     */
    com.google.protobuf.ByteString
        getChannelNoBytes();

    /**
     * <code>optional string spread_source = 4;</code>
     *
     * <pre>
     *传播来源
     * </pre>
     */
    boolean hasSpreadSource();
    /**
     * <code>optional string spread_source = 4;</code>
     *
     * <pre>
     *传播来源
     * </pre>
     */
    String getSpreadSource();
    /**
     * <code>optional string spread_source = 4;</code>
     *
     * <pre>
     *传播来源
     * </pre>
     */
    com.google.protobuf.ByteString
        getSpreadSourceBytes();

    /**
     * <code>optional string activity_no = 5;</code>
     *
     * <pre>
     *活动编号
     * </pre>
     */
    boolean hasActivityNo();
    /**
     * <code>optional string activity_no = 5;</code>
     *
     * <pre>
     *活动编号
     * </pre>
     */
    String getActivityNo();
    /**
     * <code>optional string activity_no = 5;</code>
     *
     * <pre>
     *活动编号
     * </pre>
     */
    com.google.protobuf.ByteString
        getActivityNoBytes();

    /**
     * <code>optional string inviter_qingqing_teacher_id = 6;</code>
     *
     * <pre>
     *邀请教师 qingqing_user_id
     * </pre>
     */
    boolean hasInviterQingqingTeacherId();
    /**
     * <code>optional string inviter_qingqing_teacher_id = 6;</code>
     *
     * <pre>
     *邀请教师 qingqing_user_id
     * </pre>
     */
    String getInviterQingqingTeacherId();
    /**
     * <code>optional string inviter_qingqing_teacher_id = 6;</code>
     *
     * <pre>
     *邀请教师 qingqing_user_id
     * </pre>
     */
    com.google.protobuf.ByteString
        getInviterQingqingTeacherIdBytes();

    /**
     * <code>optional int32 course_id = 7;</code>
     *
     * <pre>
     * 课程Id
     * </pre>
     */
    boolean hasCourseId();
    /**
     * <code>optional int32 course_id = 7;</code>
     *
     * <pre>
     * 课程Id
     * </pre>
     */
    int getCourseId();

    /**
     * <code>optional int32 grade_id = 8;</code>
     *
     * <pre>
     * 年级Id
     * </pre>
     */
    boolean hasGradeId();
    /**
     * <code>optional int32 grade_id = 8;</code>
     *
     * <pre>
     * 年级Id
     * </pre>
     */
    int getGradeId();

    /**
     * <code>optional string register_source = 9;</code>
     *
     * <pre>
     * 注册来源
     * </pre>
     */
    boolean hasRegisterSource();
    /**
     * <code>optional string register_source = 9;</code>
     *
     * <pre>
     * 注册来源
     * </pre>
     */
    String getRegisterSource();
    /**
     * <code>optional string register_source = 9;</code>
     *
     * <pre>
     * 注册来源
     * </pre>
     */
    com.google.protobuf.ByteString
        getRegisterSourceBytes();

    /**
     * <code>optional string qingqing_assistant_id = 10;</code>
     *
     * <pre>
     *5.9.7 指定推荐助教
     * </pre>
     */
    boolean hasQingqingAssistantId();
    /**
     * <code>optional string qingqing_assistant_id = 10;</code>
     *
     * <pre>
     *5.9.7 指定推荐助教
     * </pre>
     */
    String getQingqingAssistantId();
    /**
     * <code>optional string qingqing_assistant_id = 10;</code>
     *
     * <pre>
     *5.9.7 指定推荐助教
     * </pre>
     */
    com.google.protobuf.ByteString
        getQingqingAssistantIdBytes();

    /**
     * <code>optional string promotioner_qingqing_id = 11;</code>
     *
     * <pre>
     * 6.1.0
     * </pre>
     */
    boolean hasPromotionerQingqingId();
    /**
     * <code>optional string promotioner_qingqing_id = 11;</code>
     *
     * <pre>
     * 6.1.0
     * </pre>
     */
    String getPromotionerQingqingId();
    /**
     * <code>optional string promotioner_qingqing_id = 11;</code>
     *
     * <pre>
     * 6.1.0
     * </pre>
     */
    com.google.protobuf.ByteString
        getPromotionerQingqingIdBytes();
  }
  /**
   * Protobuf type {@code TeacherInviteStudentRegisterRequest}
   */
  public  static final class TeacherInviteStudentRegisterRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:TeacherInviteStudentRegisterRequest)
      TeacherInviteStudentRegisterRequestOrBuilder {
    // Use TeacherInviteStudentRegisterRequest.newBuilder() to construct.
    private TeacherInviteStudentRegisterRequest(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private TeacherInviteStudentRegisterRequest() {
      phoneNumber_ = "";
      captchaCode_ = "";
      channelNo_ = "";
      spreadSource_ = "";
      activityNo_ = "";
      inviterQingqingTeacherId_ = "";
      courseId_ = 0;
      gradeId_ = 0;
      registerSource_ = "";
      qingqingAssistantId_ = "";
      promotionerQingqingId_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TeacherInviteStudentRegisterRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              phoneNumber_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              captchaCode_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              channelNo_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              spreadSource_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              activityNo_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              inviterQingqingTeacherId_ = bs;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              courseId_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              gradeId_ = input.readInt32();
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              registerSource_ = bs;
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              qingqingAssistantId_ = bs;
              break;
            }
            case 90: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000400;
              promotionerQingqingId_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Teachervs.internal_static_TeacherInviteStudentRegisterRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Teachervs.internal_static_TeacherInviteStudentRegisterRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TeacherInviteStudentRegisterRequest.class, Builder.class);
    }

    private int bitField0_;
    public static final int PHONE_NUMBER_FIELD_NUMBER = 1;
    private volatile Object phoneNumber_;
    /**
     * <code>optional string phone_number = 1;</code>
     */
    public boolean hasPhoneNumber() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string phone_number = 1;</code>
     */
    public String getPhoneNumber() {
      Object ref = phoneNumber_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          phoneNumber_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string phone_number = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneNumberBytes() {
      Object ref = phoneNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        phoneNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CAPTCHA_CODE_FIELD_NUMBER = 2;
    private volatile Object captchaCode_;
    /**
     * <code>optional string captcha_code = 2;</code>
     *
     * <pre>
     * 验证码
     * </pre>
     */
    public boolean hasCaptchaCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string captcha_code = 2;</code>
     *
     * <pre>
     * 验证码
     * </pre>
     */
    public String getCaptchaCode() {
      Object ref = captchaCode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          captchaCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string captcha_code = 2;</code>
     *
     * <pre>
     * 验证码
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCaptchaCodeBytes() {
      Object ref = captchaCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        captchaCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHANNEL_NO_FIELD_NUMBER = 3;
    private volatile Object channelNo_;
    /**
     * <code>optional string channel_no = 3;</code>
     */
    public boolean hasChannelNo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string channel_no = 3;</code>
     */
    public String getChannelNo() {
      Object ref = channelNo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          channelNo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string channel_no = 3;</code>
     */
    public com.google.protobuf.ByteString
        getChannelNoBytes() {
      Object ref = channelNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        channelNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SPREAD_SOURCE_FIELD_NUMBER = 4;
    private volatile Object spreadSource_;
    /**
     * <code>optional string spread_source = 4;</code>
     *
     * <pre>
     *传播来源
     * </pre>
     */
    public boolean hasSpreadSource() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string spread_source = 4;</code>
     *
     * <pre>
     *传播来源
     * </pre>
     */
    public String getSpreadSource() {
      Object ref = spreadSource_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          spreadSource_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string spread_source = 4;</code>
     *
     * <pre>
     *传播来源
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSpreadSourceBytes() {
      Object ref = spreadSource_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        spreadSource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACTIVITY_NO_FIELD_NUMBER = 5;
    private volatile Object activityNo_;
    /**
     * <code>optional string activity_no = 5;</code>
     *
     * <pre>
     *活动编号
     * </pre>
     */
    public boolean hasActivityNo() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string activity_no = 5;</code>
     *
     * <pre>
     *活动编号
     * </pre>
     */
    public String getActivityNo() {
      Object ref = activityNo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          activityNo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string activity_no = 5;</code>
     *
     * <pre>
     *活动编号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getActivityNoBytes() {
      Object ref = activityNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        activityNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INVITER_QINGQING_TEACHER_ID_FIELD_NUMBER = 6;
    private volatile Object inviterQingqingTeacherId_;
    /**
     * <code>optional string inviter_qingqing_teacher_id = 6;</code>
     *
     * <pre>
     *邀请教师 qingqing_user_id
     * </pre>
     */
    public boolean hasInviterQingqingTeacherId() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string inviter_qingqing_teacher_id = 6;</code>
     *
     * <pre>
     *邀请教师 qingqing_user_id
     * </pre>
     */
    public String getInviterQingqingTeacherId() {
      Object ref = inviterQingqingTeacherId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          inviterQingqingTeacherId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string inviter_qingqing_teacher_id = 6;</code>
     *
     * <pre>
     *邀请教师 qingqing_user_id
     * </pre>
     */
    public com.google.protobuf.ByteString
        getInviterQingqingTeacherIdBytes() {
      Object ref = inviterQingqingTeacherId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        inviterQingqingTeacherId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COURSE_ID_FIELD_NUMBER = 7;
    private int courseId_;
    /**
     * <code>optional int32 course_id = 7;</code>
     *
     * <pre>
     * 课程Id
     * </pre>
     */
    public boolean hasCourseId() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 course_id = 7;</code>
     *
     * <pre>
     * 课程Id
     * </pre>
     */
    public int getCourseId() {
      return courseId_;
    }

    public static final int GRADE_ID_FIELD_NUMBER = 8;
    private int gradeId_;
    /**
     * <code>optional int32 grade_id = 8;</code>
     *
     * <pre>
     * 年级Id
     * </pre>
     */
    public boolean hasGradeId() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 grade_id = 8;</code>
     *
     * <pre>
     * 年级Id
     * </pre>
     */
    public int getGradeId() {
      return gradeId_;
    }

    public static final int REGISTER_SOURCE_FIELD_NUMBER = 9;
    private volatile Object registerSource_;
    /**
     * <code>optional string register_source = 9;</code>
     *
     * <pre>
     * 注册来源
     * </pre>
     */
    public boolean hasRegisterSource() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string register_source = 9;</code>
     *
     * <pre>
     * 注册来源
     * </pre>
     */
    public String getRegisterSource() {
      Object ref = registerSource_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          registerSource_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string register_source = 9;</code>
     *
     * <pre>
     * 注册来源
     * </pre>
     */
    public com.google.protobuf.ByteString
        getRegisterSourceBytes() {
      Object ref = registerSource_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        registerSource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QINGQING_ASSISTANT_ID_FIELD_NUMBER = 10;
    private volatile Object qingqingAssistantId_;
    /**
     * <code>optional string qingqing_assistant_id = 10;</code>
     *
     * <pre>
     *5.9.7 指定推荐助教
     * </pre>
     */
    public boolean hasQingqingAssistantId() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string qingqing_assistant_id = 10;</code>
     *
     * <pre>
     *5.9.7 指定推荐助教
     * </pre>
     */
    public String getQingqingAssistantId() {
      Object ref = qingqingAssistantId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          qingqingAssistantId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string qingqing_assistant_id = 10;</code>
     *
     * <pre>
     *5.9.7 指定推荐助教
     * </pre>
     */
    public com.google.protobuf.ByteString
        getQingqingAssistantIdBytes() {
      Object ref = qingqingAssistantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        qingqingAssistantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROMOTIONER_QINGQING_ID_FIELD_NUMBER = 11;
    private volatile Object promotionerQingqingId_;
    /**
     * <code>optional string promotioner_qingqing_id = 11;</code>
     *
     * <pre>
     * 6.1.0
     * </pre>
     */
    public boolean hasPromotionerQingqingId() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional string promotioner_qingqing_id = 11;</code>
     *
     * <pre>
     * 6.1.0
     * </pre>
     */
    public String getPromotionerQingqingId() {
      Object ref = promotionerQingqingId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          promotionerQingqingId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string promotioner_qingqing_id = 11;</code>
     *
     * <pre>
     * 6.1.0
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPromotionerQingqingIdBytes() {
      Object ref = promotionerQingqingId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        promotionerQingqingId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPhoneNumberBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCaptchaCodeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getChannelNoBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getSpreadSourceBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getActivityNoBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getInviterQingqingTeacherIdBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, courseId_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, gradeId_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getRegisterSourceBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getQingqingAssistantIdBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, getPromotionerQingqingIdBytes());
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPhoneNumberBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCaptchaCodeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getChannelNoBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getSpreadSourceBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getActivityNoBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getInviterQingqingTeacherIdBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, courseId_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, gradeId_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getRegisterSourceBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getQingqingAssistantIdBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getPromotionerQingqingIdBytes());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static TeacherInviteStudentRegisterRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TeacherInviteStudentRegisterRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TeacherInviteStudentRegisterRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TeacherInviteStudentRegisterRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TeacherInviteStudentRegisterRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TeacherInviteStudentRegisterRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static TeacherInviteStudentRegisterRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static TeacherInviteStudentRegisterRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static TeacherInviteStudentRegisterRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TeacherInviteStudentRegisterRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TeacherInviteStudentRegisterRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TeacherInviteStudentRegisterRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TeacherInviteStudentRegisterRequest)
        TeacherInviteStudentRegisterRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Teachervs.internal_static_TeacherInviteStudentRegisterRequest_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Teachervs.internal_static_TeacherInviteStudentRegisterRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TeacherInviteStudentRegisterRequest.class, Builder.class);
      }

      // Construct using Teachervs.TeacherInviteStudentRegisterRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        phoneNumber_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        captchaCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        channelNo_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        spreadSource_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        activityNo_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        inviterQingqingTeacherId_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        courseId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        gradeId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        registerSource_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        qingqingAssistantId_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        promotionerQingqingId_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Teachervs.internal_static_TeacherInviteStudentRegisterRequest_descriptor;
      }

      public TeacherInviteStudentRegisterRequest getDefaultInstanceForType() {
        return TeacherInviteStudentRegisterRequest.getDefaultInstance();
      }

      public TeacherInviteStudentRegisterRequest build() {
        TeacherInviteStudentRegisterRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TeacherInviteStudentRegisterRequest buildPartial() {
        TeacherInviteStudentRegisterRequest result = new TeacherInviteStudentRegisterRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.phoneNumber_ = phoneNumber_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.captchaCode_ = captchaCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.channelNo_ = channelNo_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.spreadSource_ = spreadSource_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.activityNo_ = activityNo_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.inviterQingqingTeacherId_ = inviterQingqingTeacherId_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.courseId_ = courseId_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.gradeId_ = gradeId_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.registerSource_ = registerSource_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.qingqingAssistantId_ = qingqingAssistantId_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.promotionerQingqingId_ = promotionerQingqingId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TeacherInviteStudentRegisterRequest) {
          return mergeFrom((TeacherInviteStudentRegisterRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TeacherInviteStudentRegisterRequest other) {
        if (other == TeacherInviteStudentRegisterRequest.getDefaultInstance()) return this;
        if (other.hasPhoneNumber()) {
          bitField0_ |= 0x00000001;
          phoneNumber_ = other.phoneNumber_;
          onChanged();
        }
        if (other.hasCaptchaCode()) {
          bitField0_ |= 0x00000002;
          captchaCode_ = other.captchaCode_;
          onChanged();
        }
        if (other.hasChannelNo()) {
          bitField0_ |= 0x00000004;
          channelNo_ = other.channelNo_;
          onChanged();
        }
        if (other.hasSpreadSource()) {
          bitField0_ |= 0x00000008;
          spreadSource_ = other.spreadSource_;
          onChanged();
        }
        if (other.hasActivityNo()) {
          bitField0_ |= 0x00000010;
          activityNo_ = other.activityNo_;
          onChanged();
        }
        if (other.hasInviterQingqingTeacherId()) {
          bitField0_ |= 0x00000020;
          inviterQingqingTeacherId_ = other.inviterQingqingTeacherId_;
          onChanged();
        }
        if (other.hasCourseId()) {
          setCourseId(other.getCourseId());
        }
        if (other.hasGradeId()) {
          setGradeId(other.getGradeId());
        }
        if (other.hasRegisterSource()) {
          bitField0_ |= 0x00000100;
          registerSource_ = other.registerSource_;
          onChanged();
        }
        if (other.hasQingqingAssistantId()) {
          bitField0_ |= 0x00000200;
          qingqingAssistantId_ = other.qingqingAssistantId_;
          onChanged();
        }
        if (other.hasPromotionerQingqingId()) {
          bitField0_ |= 0x00000400;
          promotionerQingqingId_ = other.promotionerQingqingId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TeacherInviteStudentRegisterRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TeacherInviteStudentRegisterRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object phoneNumber_ = "";
      /**
       * <code>optional string phone_number = 1;</code>
       */
      public boolean hasPhoneNumber() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string phone_number = 1;</code>
       */
      public String getPhoneNumber() {
        Object ref = phoneNumber_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            phoneNumber_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string phone_number = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneNumberBytes() {
        Object ref = phoneNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          phoneNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string phone_number = 1;</code>
       */
      public Builder setPhoneNumber(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        phoneNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string phone_number = 1;</code>
       */
      public Builder clearPhoneNumber() {
        bitField0_ = (bitField0_ & ~0x00000001);
        phoneNumber_ = getDefaultInstance().getPhoneNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional string phone_number = 1;</code>
       */
      public Builder setPhoneNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        phoneNumber_ = value;
        onChanged();
        return this;
      }

      private Object captchaCode_ = "";
      /**
       * <code>optional string captcha_code = 2;</code>
       *
       * <pre>
       * 验证码
       * </pre>
       */
      public boolean hasCaptchaCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string captcha_code = 2;</code>
       *
       * <pre>
       * 验证码
       * </pre>
       */
      public String getCaptchaCode() {
        Object ref = captchaCode_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            captchaCode_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string captcha_code = 2;</code>
       *
       * <pre>
       * 验证码
       * </pre>
       */
      public com.google.protobuf.ByteString
          getCaptchaCodeBytes() {
        Object ref = captchaCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          captchaCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string captcha_code = 2;</code>
       *
       * <pre>
       * 验证码
       * </pre>
       */
      public Builder setCaptchaCode(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        captchaCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string captcha_code = 2;</code>
       *
       * <pre>
       * 验证码
       * </pre>
       */
      public Builder clearCaptchaCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        captchaCode_ = getDefaultInstance().getCaptchaCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string captcha_code = 2;</code>
       *
       * <pre>
       * 验证码
       * </pre>
       */
      public Builder setCaptchaCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        captchaCode_ = value;
        onChanged();
        return this;
      }

      private Object channelNo_ = "";
      /**
       * <code>optional string channel_no = 3;</code>
       */
      public boolean hasChannelNo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string channel_no = 3;</code>
       */
      public String getChannelNo() {
        Object ref = channelNo_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            channelNo_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string channel_no = 3;</code>
       */
      public com.google.protobuf.ByteString
          getChannelNoBytes() {
        Object ref = channelNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          channelNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string channel_no = 3;</code>
       */
      public Builder setChannelNo(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        channelNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string channel_no = 3;</code>
       */
      public Builder clearChannelNo() {
        bitField0_ = (bitField0_ & ~0x00000004);
        channelNo_ = getDefaultInstance().getChannelNo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string channel_no = 3;</code>
       */
      public Builder setChannelNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        channelNo_ = value;
        onChanged();
        return this;
      }

      private Object spreadSource_ = "";
      /**
       * <code>optional string spread_source = 4;</code>
       *
       * <pre>
       *传播来源
       * </pre>
       */
      public boolean hasSpreadSource() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string spread_source = 4;</code>
       *
       * <pre>
       *传播来源
       * </pre>
       */
      public String getSpreadSource() {
        Object ref = spreadSource_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            spreadSource_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string spread_source = 4;</code>
       *
       * <pre>
       *传播来源
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSpreadSourceBytes() {
        Object ref = spreadSource_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          spreadSource_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string spread_source = 4;</code>
       *
       * <pre>
       *传播来源
       * </pre>
       */
      public Builder setSpreadSource(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        spreadSource_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string spread_source = 4;</code>
       *
       * <pre>
       *传播来源
       * </pre>
       */
      public Builder clearSpreadSource() {
        bitField0_ = (bitField0_ & ~0x00000008);
        spreadSource_ = getDefaultInstance().getSpreadSource();
        onChanged();
        return this;
      }
      /**
       * <code>optional string spread_source = 4;</code>
       *
       * <pre>
       *传播来源
       * </pre>
       */
      public Builder setSpreadSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        spreadSource_ = value;
        onChanged();
        return this;
      }

      private Object activityNo_ = "";
      /**
       * <code>optional string activity_no = 5;</code>
       *
       * <pre>
       *活动编号
       * </pre>
       */
      public boolean hasActivityNo() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string activity_no = 5;</code>
       *
       * <pre>
       *活动编号
       * </pre>
       */
      public String getActivityNo() {
        Object ref = activityNo_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            activityNo_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string activity_no = 5;</code>
       *
       * <pre>
       *活动编号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getActivityNoBytes() {
        Object ref = activityNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          activityNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string activity_no = 5;</code>
       *
       * <pre>
       *活动编号
       * </pre>
       */
      public Builder setActivityNo(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        activityNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string activity_no = 5;</code>
       *
       * <pre>
       *活动编号
       * </pre>
       */
      public Builder clearActivityNo() {
        bitField0_ = (bitField0_ & ~0x00000010);
        activityNo_ = getDefaultInstance().getActivityNo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string activity_no = 5;</code>
       *
       * <pre>
       *活动编号
       * </pre>
       */
      public Builder setActivityNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        activityNo_ = value;
        onChanged();
        return this;
      }

      private Object inviterQingqingTeacherId_ = "";
      /**
       * <code>optional string inviter_qingqing_teacher_id = 6;</code>
       *
       * <pre>
       *邀请教师 qingqing_user_id
       * </pre>
       */
      public boolean hasInviterQingqingTeacherId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string inviter_qingqing_teacher_id = 6;</code>
       *
       * <pre>
       *邀请教师 qingqing_user_id
       * </pre>
       */
      public String getInviterQingqingTeacherId() {
        Object ref = inviterQingqingTeacherId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            inviterQingqingTeacherId_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string inviter_qingqing_teacher_id = 6;</code>
       *
       * <pre>
       *邀请教师 qingqing_user_id
       * </pre>
       */
      public com.google.protobuf.ByteString
          getInviterQingqingTeacherIdBytes() {
        Object ref = inviterQingqingTeacherId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          inviterQingqingTeacherId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string inviter_qingqing_teacher_id = 6;</code>
       *
       * <pre>
       *邀请教师 qingqing_user_id
       * </pre>
       */
      public Builder setInviterQingqingTeacherId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        inviterQingqingTeacherId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string inviter_qingqing_teacher_id = 6;</code>
       *
       * <pre>
       *邀请教师 qingqing_user_id
       * </pre>
       */
      public Builder clearInviterQingqingTeacherId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        inviterQingqingTeacherId_ = getDefaultInstance().getInviterQingqingTeacherId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string inviter_qingqing_teacher_id = 6;</code>
       *
       * <pre>
       *邀请教师 qingqing_user_id
       * </pre>
       */
      public Builder setInviterQingqingTeacherIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        inviterQingqingTeacherId_ = value;
        onChanged();
        return this;
      }

      private int courseId_ ;
      /**
       * <code>optional int32 course_id = 7;</code>
       *
       * <pre>
       * 课程Id
       * </pre>
       */
      public boolean hasCourseId() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 course_id = 7;</code>
       *
       * <pre>
       * 课程Id
       * </pre>
       */
      public int getCourseId() {
        return courseId_;
      }
      /**
       * <code>optional int32 course_id = 7;</code>
       *
       * <pre>
       * 课程Id
       * </pre>
       */
      public Builder setCourseId(int value) {
        bitField0_ |= 0x00000040;
        courseId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 course_id = 7;</code>
       *
       * <pre>
       * 课程Id
       * </pre>
       */
      public Builder clearCourseId() {
        bitField0_ = (bitField0_ & ~0x00000040);
        courseId_ = 0;
        onChanged();
        return this;
      }

      private int gradeId_ ;
      /**
       * <code>optional int32 grade_id = 8;</code>
       *
       * <pre>
       * 年级Id
       * </pre>
       */
      public boolean hasGradeId() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 grade_id = 8;</code>
       *
       * <pre>
       * 年级Id
       * </pre>
       */
      public int getGradeId() {
        return gradeId_;
      }
      /**
       * <code>optional int32 grade_id = 8;</code>
       *
       * <pre>
       * 年级Id
       * </pre>
       */
      public Builder setGradeId(int value) {
        bitField0_ |= 0x00000080;
        gradeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 grade_id = 8;</code>
       *
       * <pre>
       * 年级Id
       * </pre>
       */
      public Builder clearGradeId() {
        bitField0_ = (bitField0_ & ~0x00000080);
        gradeId_ = 0;
        onChanged();
        return this;
      }

      private Object registerSource_ = "";
      /**
       * <code>optional string register_source = 9;</code>
       *
       * <pre>
       * 注册来源
       * </pre>
       */
      public boolean hasRegisterSource() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string register_source = 9;</code>
       *
       * <pre>
       * 注册来源
       * </pre>
       */
      public String getRegisterSource() {
        Object ref = registerSource_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            registerSource_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string register_source = 9;</code>
       *
       * <pre>
       * 注册来源
       * </pre>
       */
      public com.google.protobuf.ByteString
          getRegisterSourceBytes() {
        Object ref = registerSource_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          registerSource_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string register_source = 9;</code>
       *
       * <pre>
       * 注册来源
       * </pre>
       */
      public Builder setRegisterSource(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        registerSource_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string register_source = 9;</code>
       *
       * <pre>
       * 注册来源
       * </pre>
       */
      public Builder clearRegisterSource() {
        bitField0_ = (bitField0_ & ~0x00000100);
        registerSource_ = getDefaultInstance().getRegisterSource();
        onChanged();
        return this;
      }
      /**
       * <code>optional string register_source = 9;</code>
       *
       * <pre>
       * 注册来源
       * </pre>
       */
      public Builder setRegisterSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        registerSource_ = value;
        onChanged();
        return this;
      }

      private Object qingqingAssistantId_ = "";
      /**
       * <code>optional string qingqing_assistant_id = 10;</code>
       *
       * <pre>
       *5.9.7 指定推荐助教
       * </pre>
       */
      public boolean hasQingqingAssistantId() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string qingqing_assistant_id = 10;</code>
       *
       * <pre>
       *5.9.7 指定推荐助教
       * </pre>
       */
      public String getQingqingAssistantId() {
        Object ref = qingqingAssistantId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            qingqingAssistantId_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string qingqing_assistant_id = 10;</code>
       *
       * <pre>
       *5.9.7 指定推荐助教
       * </pre>
       */
      public com.google.protobuf.ByteString
          getQingqingAssistantIdBytes() {
        Object ref = qingqingAssistantId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          qingqingAssistantId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string qingqing_assistant_id = 10;</code>
       *
       * <pre>
       *5.9.7 指定推荐助教
       * </pre>
       */
      public Builder setQingqingAssistantId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        qingqingAssistantId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string qingqing_assistant_id = 10;</code>
       *
       * <pre>
       *5.9.7 指定推荐助教
       * </pre>
       */
      public Builder clearQingqingAssistantId() {
        bitField0_ = (bitField0_ & ~0x00000200);
        qingqingAssistantId_ = getDefaultInstance().getQingqingAssistantId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string qingqing_assistant_id = 10;</code>
       *
       * <pre>
       *5.9.7 指定推荐助教
       * </pre>
       */
      public Builder setQingqingAssistantIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        qingqingAssistantId_ = value;
        onChanged();
        return this;
      }

      private Object promotionerQingqingId_ = "";
      /**
       * <code>optional string promotioner_qingqing_id = 11;</code>
       *
       * <pre>
       * 6.1.0
       * </pre>
       */
      public boolean hasPromotionerQingqingId() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional string promotioner_qingqing_id = 11;</code>
       *
       * <pre>
       * 6.1.0
       * </pre>
       */
      public String getPromotionerQingqingId() {
        Object ref = promotionerQingqingId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            promotionerQingqingId_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string promotioner_qingqing_id = 11;</code>
       *
       * <pre>
       * 6.1.0
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPromotionerQingqingIdBytes() {
        Object ref = promotionerQingqingId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          promotionerQingqingId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string promotioner_qingqing_id = 11;</code>
       *
       * <pre>
       * 6.1.0
       * </pre>
       */
      public Builder setPromotionerQingqingId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        promotionerQingqingId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string promotioner_qingqing_id = 11;</code>
       *
       * <pre>
       * 6.1.0
       * </pre>
       */
      public Builder clearPromotionerQingqingId() {
        bitField0_ = (bitField0_ & ~0x00000400);
        promotionerQingqingId_ = getDefaultInstance().getPromotionerQingqingId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string promotioner_qingqing_id = 11;</code>
       *
       * <pre>
       * 6.1.0
       * </pre>
       */
      public Builder setPromotionerQingqingIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        promotionerQingqingId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TeacherInviteStudentRegisterRequest)
    }

    // @@protoc_insertion_point(class_scope:TeacherInviteStudentRegisterRequest)
    private static final TeacherInviteStudentRegisterRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TeacherInviteStudentRegisterRequest();
    }

    public static TeacherInviteStudentRegisterRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<TeacherInviteStudentRegisterRequest> PARSER =
        new com.google.protobuf.AbstractParser<TeacherInviteStudentRegisterRequest>() {
      public TeacherInviteStudentRegisterRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new TeacherInviteStudentRegisterRequest(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @Override
    public com.google.protobuf.Parser<TeacherInviteStudentRegisterRequest> getParserForType() {
      return PARSER;
    }

    public TeacherInviteStudentRegisterRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TeacherInviteStudentRegisterRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TeacherInviteStudentRegisterRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022v1/Teachervs.proto\"\264\002\n#TeacherInviteSt" +
      "udentRegisterRequest\022\024\n\014phone_number\030\001 \001" +
      "(\t\022\024\n\014captcha_code\030\002 \001(\t\022\022\n\nchannel_no\030\003" +
      " \001(\t\022\025\n\rspread_source\030\004 \001(\t\022\023\n\013activity_" +
      "no\030\005 \001(\t\022#\n\033inviter_qingqing_teacher_id\030" +
      "\006 \001(\t\022\021\n\tcourse_id\030\007 \001(\005\022\020\n\010grade_id\030\010 \001" +
      "(\005\022\027\n\017register_source\030\t \001(\t\022\035\n\025qingqing_" +
      "assistant_id\030\n \001(\t\022\037\n\027promotioner_qingqi" +
      "ng_id\030\013 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TeacherInviteStudentRegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TeacherInviteStudentRegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_TeacherInviteStudentRegisterRequest_descriptor,
        new String[] { "PhoneNumber", "CaptchaCode", "ChannelNo", "SpreadSource", "ActivityNo", "InviterQingqingTeacherId", "CourseId", "GradeId", "RegisterSource", "QingqingAssistantId", "PromotionerQingqingId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
